apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: "15s"
    version: 1
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
    version: 1
    editable: true

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    jsonData:
      tracesToLogs:
        datasourceUid: 'Loki' # UID of the Loki datasource defined above (Grafana generates UIDs, linking by name might require manual setup first or knowing the UID)
        tags: ['job', 'instance', 'container_name']
        mappedTags: [{ key: 'service.name', value: 'job' }]
        spanStartTimeShift: '1h' # Adjust as needed
        spanEndTimeShift: '1h'   # Adjust as needed
    version: 1
    editable: true 