server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Remove the restrictive filters that might be excluding your containers
      # Instead, add a default label for all containers
      - action: replace
        target_label: app
        replacement: "expense-insights"
      # Use the container name as the instance label
      - source_labels: [__meta_docker_container_name]
        regex: "/(.*)"
        target_label: instance
      # Add container ID as a label
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
      # Add job label based on service if it exists, otherwise use a default
      - source_labels: [__meta_docker_container_label_service]
        target_label: job
        regex: (.+)
        replacement: ${1}
      # Default job label if service label doesn't exist
      - action: replace
        target_label: job
        replacement: "docker-logs"
        source_labels: [job]
        regex: ^$
      # Add container name as a label
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
      # Example: Add a 'host' label based on the Docker host (if running Promtail in a container)
      # This might require setting an environment variable on the Promtail container itself
      # - action: replace
      #   target_label: host
      #   replacement: ${HOSTNAME} # Assuming HOSTNAME env var is set for Promtail container 